name: GenixPlugin
version: '1.0'
main: com.Genix.Main
api-version: '1.20'

commands:
  tempban:
    discription: self explanatory
    usage: is bro stupid
  tempmute:
    discription: self explanatory
    usage: is bro stupid
  ban:
    discription: self explanatory
    usage: is bro stupid
  mute:
    discription: self explanatory
    usage: is bro stupid
  kick:
    discription: self explanatory
    usage: is bro stupid
  unban:
    discription: self explanatory
    usage: is bro stupid
  unmute:
    discription: self explanatory
    usage: is bro stupid

  skull:
    discription: get testing head
    usage: /skull

  report:
    discription: report a player for breaking the rules
    usage: /report <player>